default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
  username: <%= ENV.fetch("DATABASE_USER", "c3ads") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "c3ads") %>

development:
  <<: *default
  database: c3ads_development

test:
  <<: *default
  database: c3ads_test

production:
  <<: *default
  database: c3ads_production
